  import 'package:hackathon/core/core/model/event_model.dart';

List<EventModel> events = [
    EventModel(
        id: "1",
        name: "event1",
        description: "description",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "2",
        name: "fevent2",
        description: "description1",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "3",
        name: "devent3",
        description: "description2",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "4",
        name: "cevent4",
        description: "description3",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "5",
        name: "gevent5",
        description: "descriptio4",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "6",
        name: "gevent6",
        description: "description5",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "7",
        name: "cevent6",
        description: "description6",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
    EventModel(
        id: "8",
        name: "fevent7",
        description: "description7",
        image: "",
        location: "Antalya",
        date: "07.11.2022",
        time: "11:40 am",
        category: "Publi Meet"),
  ];
